name: qiandao

on:
  schedule:
    - cron: "00 9 * * *"
  watch:
    types: [started]

jobs:
  auto_qidiao:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: python3
      run: |
        /usr/bin/python3 main.py